************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_retiros_mrcs
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_retiros_mrcs"
CONTENIDO.CLSETIQUETA1.Name = "CLSETIQUETA1"
CONTENIDO.sel_clientes.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.sel_clientes.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.sel_clientes.Name = "sel_clientes"
CONTENIDO.CLSLINEA1.Name = "CLSLINEA1"
CONTENIDO.CLSETIQUETA2.Name = "CLSETIQUETA2"
CONTENIDO.sel_vendedor.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.sel_vendedor.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.sel_vendedor.Name = "sel_vendedor"
CONTENIDO.CLSETIQUETA3.Name = "CLSETIQUETA3"
CONTENIDO.SEL_ARTICULOS.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.SEL_ARTICULOS.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.SEL_ARTICULOS.Name = "SEL_ARTICULOS"
CONTENIDO.CLSETIQUETA4.Name = "CLSETIQUETA4"
CONTENIDO.TXTCANTIDAD.Name = "TXTCANTIDAD"
CONTENIDO.BTNACEPTAR.Name = "BTNACEPTAR"
CONTENIDO.BTNAGREGAR.Name = "BTNAGREGAR"
CONTENIDO.GRDDETALLE.COLUMN1.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN1.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN1.CLSCHECKBOX1.Alignment = 0
CONTENIDO.GRDDETALLE.COLUMN1.CLSCHECKBOX1.Name = "CLSCHECKBOX1"
CONTENIDO.GRDDETALLE.COLUMN1.Name = "COLUMN1"
CONTENIDO.GRDDETALLE.COLUMN2.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN2.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN2.Name = "COLUMN2"
CONTENIDO.GRDDETALLE.COLUMN3.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN3.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN3.Name = "COLUMN3"
CONTENIDO.GRDDETALLE.COLUMN4.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN4.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN4.Name = "COLUMN4"
CONTENIDO.GRDDETALLE.COLUMN5.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN5.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN5.Name = "COLUMN5"
CONTENIDO.GRDDETALLE.COLUMN6.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN6.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN6.Name = "COLUMN6"
CONTENIDO.GRDDETALLE.COLUMN7.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN7.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN7.Name = "COLUMN7"
CONTENIDO.GRDDETALLE.COLUMN8.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN8.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN8.Name = "COLUMN8"
CONTENIDO.GRDDETALLE.COLUMN9.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN9.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN9.Name = "COLUMN9"
CONTENIDO.GRDDETALLE.COLUMN10.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN10.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN10.Name = "COLUMN10"
CONTENIDO.GRDDETALLE.COLUMN11.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN11.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN11.Name = "COLUMN11"
CONTENIDO.GRDDETALLE.COLUMN12.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN12.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN12.Name = "COLUMN12"
CONTENIDO.GRDDETALLE.COLUMN13.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN13.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN13.Name = "COLUMN13"
CONTENIDO.GRDDETALLE.COLUMN14.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN14.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN14.Name = "COLUMN14"
CONTENIDO.GRDDETALLE.COLUMN15.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN15.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN15.Name = "COLUMN15"
CONTENIDO.GRDDETALLE.COLUMN16.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN16.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN16.Name = "COLUMN16"
CONTENIDO.GRDDETALLE.COLUMN17.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN17.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN17.Name = "COLUMN17"
CONTENIDO.GRDDETALLE.COLUMN18.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN18.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN18.Name = "COLUMN18"
CONTENIDO.GRDDETALLE.COLUMN19.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN19.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN19.Name = "COLUMN19"
CONTENIDO.GRDDETALLE.COLUMN20.HEADER1.Name = "HEADER1"
CONTENIDO.GRDDETALLE.COLUMN20.TEXT1.Name = "TEXT1"
CONTENIDO.GRDDETALLE.COLUMN20.Name = "COLUMN20"
CONTENIDO.GRDDETALLE.Name = "GRDDETALLE"
CONTENIDO.BTNGRABAR.Name = "BTNGRABAR"
CONTENIDO.BTNCANCELAR.Name = "BTNCANCELAR"
CONTENIDO.BTNCERRAR.Name = "BTNCERRAR"
CONTENIDO.CLSETIQUETA5.Name = "CLSETIQUETA5"
CONTENIDO.txtRetiro.Name = "txtRetiro"
CONTENIDO.btnFacturar.Name = "btnFacturar"
CONTENIDO.btnVerMorosidad.Name = "btnVerMorosidad"
CONTENIDO.chkMarcarTodos.Alignment = 0
CONTENIDO.chkMarcarTodos.Name = "chkMarcarTodos"
CONTENIDO.lblSaldo.Name = "lblSaldo"
CONTENIDO.Name = "CONTENIDO"
retiros.Name = "retiros"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


