************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_artped_byprov
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_artped_byprov"
contenido.pgf.ErasePage = .T.
contenido.pgf.Page1.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgf.Page1.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgf.Page1.txtFechaDesde.Name = "txtFechaDesde"
contenido.pgf.Page1.txtFechaHasta.Name = "txtFechaHasta"
contenido.pgf.Page1.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.pgf.Page1.Clsetiqueta4.Name = "Clsetiqueta4"
contenido.pgf.Page1.sel_proveedor_desde.txtCodigo.Name = "txtCodigo"
contenido.pgf.Page1.sel_proveedor_desde.txtDescripcion.Name = "txtDescripcion"
contenido.pgf.Page1.sel_proveedor_desde.Name = "sel_proveedor_desde"
contenido.pgf.Page1.Selector_tabla1.txtCodigo.Name = "txtCodigo"
contenido.pgf.Page1.Selector_tabla1.txtDescripcion.Name = "txtDescripcion"
contenido.pgf.Page1.Selector_tabla1.Name = "Selector_tabla1"
contenido.pgf.Page1.btnSiguiente.Name = "btnSiguiente"
contenido.pgf.Page1.Clscancelar1.Name = "Clscancelar1"
contenido.pgf.Page1.Name = "Page1"
contenido.pgf.Page2.grdProveedores.COLUMN1.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN1.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN1.Name = "COLUMN1"
contenido.pgf.Page2.grdProveedores.COLUMN2.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN2.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN2.Name = "COLUMN2"
contenido.pgf.Page2.grdProveedores.COLUMN3.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN3.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN3.Name = "COLUMN3"
contenido.pgf.Page2.grdProveedores.COLUMN4.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN4.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN4.Name = "COLUMN4"
contenido.pgf.Page2.grdProveedores.COLUMN5.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN5.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN5.Name = "COLUMN5"
contenido.pgf.Page2.grdProveedores.COLUMN6.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN6.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN6.Name = "COLUMN6"
contenido.pgf.Page2.grdProveedores.COLUMN7.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN7.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN7.Name = "COLUMN7"
contenido.pgf.Page2.grdProveedores.COLUMN8.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN8.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN8.Name = "COLUMN8"
contenido.pgf.Page2.grdProveedores.COLUMN9.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN9.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN9.Name = "COLUMN9"
contenido.pgf.Page2.grdProveedores.COLUMN10.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN10.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN10.Name = "COLUMN10"
contenido.pgf.Page2.grdProveedores.COLUMN11.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN11.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN11.Name = "COLUMN11"
contenido.pgf.Page2.grdProveedores.COLUMN12.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN12.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN12.Name = "COLUMN12"
contenido.pgf.Page2.grdProveedores.COLUMN13.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN13.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN13.Name = "COLUMN13"
contenido.pgf.Page2.grdProveedores.COLUMN14.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN14.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN14.Name = "COLUMN14"
contenido.pgf.Page2.grdProveedores.COLUMN15.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN15.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN15.Name = "COLUMN15"
contenido.pgf.Page2.grdProveedores.COLUMN16.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN16.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN16.Name = "COLUMN16"
contenido.pgf.Page2.grdProveedores.COLUMN17.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN17.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN17.Name = "COLUMN17"
contenido.pgf.Page2.grdProveedores.COLUMN18.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN18.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN18.Name = "COLUMN18"
contenido.pgf.Page2.grdProveedores.COLUMN19.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN19.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN19.Name = "COLUMN19"
contenido.pgf.Page2.grdProveedores.COLUMN20.Header1.Name = "Header1"
contenido.pgf.Page2.grdProveedores.COLUMN20.Text1.Name = "Text1"
contenido.pgf.Page2.grdProveedores.COLUMN20.Name = "COLUMN20"
contenido.pgf.Page2.grdProveedores.Name = "grdProveedores"
contenido.pgf.Page2.grdArticulos.COLUMN1.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN1.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN1.Name = "COLUMN1"
contenido.pgf.Page2.grdArticulos.COLUMN2.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN2.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN2.Name = "COLUMN2"
contenido.pgf.Page2.grdArticulos.COLUMN3.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN3.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN3.Name = "COLUMN3"
contenido.pgf.Page2.grdArticulos.COLUMN4.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN4.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN4.Name = "COLUMN4"
contenido.pgf.Page2.grdArticulos.COLUMN5.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN5.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN5.Name = "COLUMN5"
contenido.pgf.Page2.grdArticulos.COLUMN6.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN6.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN6.Name = "COLUMN6"
contenido.pgf.Page2.grdArticulos.COLUMN7.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN7.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN7.Name = "COLUMN7"
contenido.pgf.Page2.grdArticulos.COLUMN8.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN8.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN8.Name = "COLUMN8"
contenido.pgf.Page2.grdArticulos.COLUMN9.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN9.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN9.Name = "COLUMN9"
contenido.pgf.Page2.grdArticulos.COLUMN10.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN10.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN10.Name = "COLUMN10"
contenido.pgf.Page2.grdArticulos.COLUMN11.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN11.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN11.Name = "COLUMN11"
contenido.pgf.Page2.grdArticulos.COLUMN12.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN12.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN12.Name = "COLUMN12"
contenido.pgf.Page2.grdArticulos.COLUMN13.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN13.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN13.Name = "COLUMN13"
contenido.pgf.Page2.grdArticulos.COLUMN14.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN14.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN14.Name = "COLUMN14"
contenido.pgf.Page2.grdArticulos.COLUMN15.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN15.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN15.Name = "COLUMN15"
contenido.pgf.Page2.grdArticulos.COLUMN16.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN16.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN16.Name = "COLUMN16"
contenido.pgf.Page2.grdArticulos.COLUMN17.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN17.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN17.Name = "COLUMN17"
contenido.pgf.Page2.grdArticulos.COLUMN18.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN18.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN18.Name = "COLUMN18"
contenido.pgf.Page2.grdArticulos.COLUMN19.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN19.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN19.Name = "COLUMN19"
contenido.pgf.Page2.grdArticulos.COLUMN20.Header1.Name = "Header1"
contenido.pgf.Page2.grdArticulos.COLUMN20.Text1.Name = "Text1"
contenido.pgf.Page2.grdArticulos.COLUMN20.Name = "COLUMN20"
contenido.pgf.Page2.grdArticulos.Name = "grdArticulos"
contenido.pgf.Page2.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgf.Page2.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgf.Page2.btnImprimir.Name = "btnImprimir"
contenido.pgf.Page2.Name = "Page2"
contenido.pgf.Name = "pgf"
contenido.btnCerrar.Name = "btnCerrar"
contenido.Name = "contenido"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


