************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmdepositos
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frmdepositos"
HERRAMIENTAS.CMDNUEVO.Name = "CMDNUEVO"
HERRAMIENTAS.CMDEDITAR.Name = "CMDEDITAR"
HERRAMIENTAS.CMDELIMINAR.Name = "CMDELIMINAR"
HERRAMIENTAS.CMDCERRAR.Name = "CMDCERRAR"
HERRAMIENTAS.CMDGRABAR.Name = "CMDGRABAR"
HERRAMIENTAS.CMDCANCELAR.Name = "CMDCANCELAR"
HERRAMIENTAS.cmdExcel.Name = "cmdExcel"
HERRAMIENTAS.Name = "HERRAMIENTAS"
PGF.ErasePage = .T.
PGF.Page1.GRDDATOS.COLUMN1.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN1.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN1.Name = "COLUMN1"
PGF.Page1.GRDDATOS.COLUMN2.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN2.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN2.Name = "COLUMN2"
PGF.Page1.GRDDATOS.COLUMN3.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN3.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN3.Name = "COLUMN3"
PGF.Page1.GRDDATOS.COLUMN4.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN4.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN4.Name = "COLUMN4"
PGF.Page1.GRDDATOS.COLUMN5.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN5.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN5.Name = "COLUMN5"
PGF.Page1.GRDDATOS.COLUMN6.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN6.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN6.Name = "COLUMN6"
PGF.Page1.GRDDATOS.COLUMN7.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN7.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN7.Name = "COLUMN7"
PGF.Page1.GRDDATOS.COLUMN8.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN8.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN8.Name = "COLUMN8"
PGF.Page1.GRDDATOS.COLUMN9.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN9.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN9.Name = "COLUMN9"
PGF.Page1.GRDDATOS.COLUMN10.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN10.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN10.Name = "COLUMN10"
PGF.Page1.GRDDATOS.COLUMN11.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN11.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN11.Name = "COLUMN11"
PGF.Page1.GRDDATOS.COLUMN12.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN12.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN12.Name = "COLUMN12"
PGF.Page1.GRDDATOS.COLUMN13.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN13.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN13.Name = "COLUMN13"
PGF.Page1.GRDDATOS.COLUMN14.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN14.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN14.Name = "COLUMN14"
PGF.Page1.GRDDATOS.COLUMN15.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN15.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN15.Name = "COLUMN15"
PGF.Page1.GRDDATOS.COLUMN16.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN16.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN16.Name = "COLUMN16"
PGF.Page1.GRDDATOS.COLUMN17.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN17.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN17.Name = "COLUMN17"
PGF.Page1.GRDDATOS.COLUMN18.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN18.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN18.Name = "COLUMN18"
PGF.Page1.GRDDATOS.COLUMN19.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN19.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN19.Name = "COLUMN19"
PGF.Page1.GRDDATOS.COLUMN20.HEADER1.Name = "HEADER1"
PGF.Page1.GRDDATOS.COLUMN20.Text1.Name = "Text1"
PGF.Page1.GRDDATOS.COLUMN20.Name = "COLUMN20"
PGF.Page1.GRDDATOS.Name = "GRDDATOS"
PGF.Page1.Name = "Page1"
PGF.Page2.CNT_FIELDS.Clsetiqueta1.Name = "Clsetiqueta1"
PGF.Page2.CNT_FIELDS.Clsetiqueta2.Name = "Clsetiqueta2"
PGF.Page2.CNT_FIELDS.txtCodigo.Name = "txtCodigo"
PGF.Page2.CNT_FIELDS.txtDescriocion.Name = "txtDescriocion"
PGF.Page2.CNT_FIELDS.Name = "CNT_FIELDS"
PGF.Page2.Name = "Page2"
PGF.Name = "PGF"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


