************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_updater_net
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_updater_net"
Pages.ErasePage = .T.
Pages.Page1.Clsetiqueta1.Name = "Clsetiqueta1"
Pages.Page1.sel_proveedor.txtCodigo.Name = "txtCodigo"
Pages.Page1.sel_proveedor.txtDescripcion.Name = "txtDescripcion"
Pages.Page1.sel_proveedor.Name = "sel_proveedor"
Pages.Page1.Clsetiqueta2.Name = "Clsetiqueta2"
Pages.Page1.Clsetiqueta3.Name = "Clsetiqueta3"
Pages.Page1.Clsetiqueta4.Name = "Clsetiqueta4"
Pages.Page1.Clsetiqueta5.Name = "Clsetiqueta5"
Pages.Page1.txtBonif1.Name = "txtBonif1"
Pages.Page1.txtBonif2.Name = "txtBonif2"
Pages.Page1.txtBonif3.Name = "txtBonif3"
Pages.Page1.txtBonif4.Name = "txtBonif4"
Pages.Page1.Clsetiqueta6.Name = "Clsetiqueta6"
Pages.Page1.Clsetiqueta7.Name = "Clsetiqueta7"
Pages.Page1.txtMargenMay.Name = "txtMargenMay"
Pages.Page1.txtMargenMin.Name = "txtMargenMin"
Pages.Page1.btnProcesar.Name = "btnProcesar"
Pages.Page1.Clsetiqueta8.Name = "Clsetiqueta8"
Pages.Page1.txtFileName.Name = "txtFileName"
Pages.Page1.Clsetiqueta9.Name = "Clsetiqueta9"
Pages.Page1.txtFecha.Name = "txtFecha"
Pages.Page1.grdVistaPrevia.COLUMN1.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN1.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN1.Name = "COLUMN1"
Pages.Page1.grdVistaPrevia.COLUMN2.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN2.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN2.Name = "COLUMN2"
Pages.Page1.grdVistaPrevia.COLUMN3.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN3.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN3.Name = "COLUMN3"
Pages.Page1.grdVistaPrevia.COLUMN4.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN4.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN4.Name = "COLUMN4"
Pages.Page1.grdVistaPrevia.COLUMN5.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN5.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN5.Name = "COLUMN5"
Pages.Page1.grdVistaPrevia.COLUMN6.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN6.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN6.Name = "COLUMN6"
Pages.Page1.grdVistaPrevia.COLUMN7.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN7.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN7.Name = "COLUMN7"
Pages.Page1.grdVistaPrevia.COLUMN8.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN8.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN8.Name = "COLUMN8"
Pages.Page1.grdVistaPrevia.COLUMN9.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN9.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN9.Name = "COLUMN9"
Pages.Page1.grdVistaPrevia.COLUMN10.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN10.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN10.Name = "COLUMN10"
Pages.Page1.grdVistaPrevia.COLUMN11.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN11.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN11.Name = "COLUMN11"
Pages.Page1.grdVistaPrevia.COLUMN12.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN12.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN12.Name = "COLUMN12"
Pages.Page1.grdVistaPrevia.COLUMN13.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN13.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN13.Name = "COLUMN13"
Pages.Page1.grdVistaPrevia.COLUMN14.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN14.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN14.Name = "COLUMN14"
Pages.Page1.grdVistaPrevia.COLUMN15.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN15.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN15.Name = "COLUMN15"
Pages.Page1.grdVistaPrevia.COLUMN16.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN16.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN16.Name = "COLUMN16"
Pages.Page1.grdVistaPrevia.COLUMN17.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN17.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN17.Name = "COLUMN17"
Pages.Page1.grdVistaPrevia.COLUMN18.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN18.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN18.Name = "COLUMN18"
Pages.Page1.grdVistaPrevia.COLUMN19.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN19.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN19.Name = "COLUMN19"
Pages.Page1.grdVistaPrevia.COLUMN20.Header1.Name = "Header1"
Pages.Page1.grdVistaPrevia.COLUMN20.Text1.Name = "Text1"
Pages.Page1.grdVistaPrevia.COLUMN20.Name = "COLUMN20"
Pages.Page1.grdVistaPrevia.Name = "grdVistaPrevia"
Pages.Page1.Clsetiqueta10.Name = "Clsetiqueta10"
Pages.Page1.Name = "Page1"
Pages.Page2.Clsetiqueta1.Name = "Clsetiqueta1"
Pages.Page2.Clsetiqueta2.Name = "Clsetiqueta2"
Pages.Page2.txtActualizados.Name = "txtActualizados"
Pages.Page2.txtNuevos.Name = "txtNuevos"
Pages.Page2.Clsetiqueta3.Name = "Clsetiqueta3"
Pages.Page2.grdArticulos.COLUMN1.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN1.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN1.Name = "COLUMN1"
Pages.Page2.grdArticulos.COLUMN2.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN2.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN2.Name = "COLUMN2"
Pages.Page2.grdArticulos.COLUMN3.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN3.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN3.Name = "COLUMN3"
Pages.Page2.grdArticulos.COLUMN4.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN4.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN4.Name = "COLUMN4"
Pages.Page2.grdArticulos.COLUMN5.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN5.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN5.Name = "COLUMN5"
Pages.Page2.grdArticulos.COLUMN6.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN6.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN6.Name = "COLUMN6"
Pages.Page2.grdArticulos.COLUMN7.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN7.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN7.Name = "COLUMN7"
Pages.Page2.grdArticulos.COLUMN8.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN8.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN8.Name = "COLUMN8"
Pages.Page2.grdArticulos.COLUMN9.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN9.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN9.Name = "COLUMN9"
Pages.Page2.grdArticulos.COLUMN10.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN10.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN10.Name = "COLUMN10"
Pages.Page2.grdArticulos.COLUMN11.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN11.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN11.Name = "COLUMN11"
Pages.Page2.grdArticulos.COLUMN12.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN12.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN12.Name = "COLUMN12"
Pages.Page2.grdArticulos.COLUMN13.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN13.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN13.Name = "COLUMN13"
Pages.Page2.grdArticulos.COLUMN14.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN14.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN14.Name = "COLUMN14"
Pages.Page2.grdArticulos.COLUMN15.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN15.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN15.Name = "COLUMN15"
Pages.Page2.grdArticulos.COLUMN16.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN16.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN16.Name = "COLUMN16"
Pages.Page2.grdArticulos.COLUMN17.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN17.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN17.Name = "COLUMN17"
Pages.Page2.grdArticulos.COLUMN18.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN18.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN18.Name = "COLUMN18"
Pages.Page2.grdArticulos.COLUMN19.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN19.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN19.Name = "COLUMN19"
Pages.Page2.grdArticulos.COLUMN20.Header1.Name = "Header1"
Pages.Page2.grdArticulos.COLUMN20.Text1.Name = "Text1"
Pages.Page2.grdArticulos.COLUMN20.Name = "COLUMN20"
Pages.Page2.grdArticulos.Name = "grdArticulos"
Pages.Page2.btnGrabar.Name = "btnGrabar"
Pages.Page2.btnCancelar.Name = "btnCancelar"
Pages.Page2.Name = "Page2"
Pages.Name = "Pages"
Clscerrar1.Name = "Clscerrar1"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0
Arial, 1, 9, 6, 15, 12, 32, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0

*** METODOS ***


