************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_emision_remitos
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_emision_remitos"
contenido.cnt_parametros.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.cnt_parametros.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.cnt_parametros.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.cnt_parametros.Clsetiqueta4.Name = "Clsetiqueta4"
contenido.cnt_parametros.sel_cliente.txtCodigo.Name = "txtCodigo"
contenido.cnt_parametros.sel_cliente.txtDescripcion.Name = "txtDescripcion"
contenido.cnt_parametros.sel_cliente.Name = "sel_cliente"
contenido.cnt_parametros.txt_fecha_desde.Name = "txt_fecha_desde"
contenido.cnt_parametros.txt_fecha_hasta.Name = "txt_fecha_hasta"
contenido.cnt_parametros.btnBuscar.Name = "btnBuscar"
contenido.cnt_parametros.btnCancelar.Name = "btnCancelar"
contenido.cnt_parametros.Name = "cnt_parametros"
contenido.cnt_facturas.pgf.ErasePage = .T.
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN1.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN1.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN1.Name = "COLUMN1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN2.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN2.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN2.Name = "COLUMN2"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN3.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN3.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN3.Name = "COLUMN3"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN4.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN4.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN4.Name = "COLUMN4"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN5.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN5.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN5.Name = "COLUMN5"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN6.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN6.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN6.Name = "COLUMN6"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN7.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN7.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN7.Name = "COLUMN7"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN8.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN8.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN8.Name = "COLUMN8"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN9.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN9.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN9.Name = "COLUMN9"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN10.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN10.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN10.Name = "COLUMN10"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN11.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN11.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN11.Name = "COLUMN11"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN12.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN12.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN12.Name = "COLUMN12"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN13.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN13.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN13.Name = "COLUMN13"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN14.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN14.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN14.Name = "COLUMN14"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN15.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN15.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN15.Name = "COLUMN15"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN16.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN16.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN16.Name = "COLUMN16"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN17.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN17.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN17.Name = "COLUMN17"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN18.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN18.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN18.Name = "COLUMN18"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN19.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN19.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN19.Name = "COLUMN19"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN20.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN20.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page1.grd_facturas.COLUMN20.Name = "COLUMN20"
contenido.cnt_facturas.pgf.Page1.grd_facturas.Name = "grd_facturas"
contenido.cnt_facturas.pgf.Page1.Name = "Page1"
contenido.cnt_facturas.pgf.Page2.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.cnt_facturas.pgf.Page2.sel_transporte.txtCodigo.Name = "txtCodigo"
contenido.cnt_facturas.pgf.Page2.sel_transporte.txtDescripcion.Name = "txtDescripcion"
contenido.cnt_facturas.pgf.Page2.sel_transporte.Name = "sel_transporte"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN1.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN1.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN1.Name = "COLUMN1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN2.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN2.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN2.Name = "COLUMN2"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN3.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN3.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN3.Name = "COLUMN3"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN4.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN4.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN4.Name = "COLUMN4"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN5.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN5.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN5.Name = "COLUMN5"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN6.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN6.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN6.Name = "COLUMN6"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN7.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN7.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN7.Name = "COLUMN7"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN8.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN8.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN8.Name = "COLUMN8"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN9.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN9.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN9.Name = "COLUMN9"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN10.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN10.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN10.Name = "COLUMN10"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN11.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN11.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN11.Name = "COLUMN11"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN12.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN12.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN12.Name = "COLUMN12"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN13.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN13.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN13.Name = "COLUMN13"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN14.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN14.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN14.Name = "COLUMN14"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN15.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN15.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN15.Name = "COLUMN15"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN16.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN16.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN16.Name = "COLUMN16"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN17.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN17.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN17.Name = "COLUMN17"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN18.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN18.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN18.Name = "COLUMN18"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN19.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN19.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN19.Name = "COLUMN19"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN20.Header1.Name = "Header1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN20.Text1.Name = "Text1"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.COLUMN20.Name = "COLUMN20"
contenido.cnt_facturas.pgf.Page2.grd_rto_item.Name = "grd_rto_item"
contenido.cnt_facturas.pgf.Page2.Clsgrabar1.Name = "Clsgrabar1"
contenido.cnt_facturas.pgf.Page2.Clscancelar1.Name = "Clscancelar1"
contenido.cnt_facturas.pgf.Page2.Name = "Page2"
contenido.cnt_facturas.pgf.Name = "pgf"
contenido.cnt_facturas.Name = "cnt_facturas"
contenido.Name = "contenido"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


