************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmCotizacion
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Caption = "Confección de Cotizaciones"
cbte = COT
Name = "frmCotizacion"
CONTENIDO.CLSETIQUETA1.Name = "CLSETIQUETA1"
CONTENIDO.SEL_CLIENTE.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.SEL_CLIENTE.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.SEL_CLIENTE.Name = "SEL_CLIENTE"
CONTENIDO.CLSETIQUETA2.Name = "CLSETIQUETA2"
CONTENIDO.CLSETIQUETA3.Name = "CLSETIQUETA3"
CONTENIDO.TXTSITIVA.Name = "TXTSITIVA"
CONTENIDO.SEL_FORMAPAGO.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.SEL_FORMAPAGO.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.SEL_FORMAPAGO.Name = "SEL_FORMAPAGO"
CONTENIDO.CLSLINEA1.Name = "CLSLINEA1"
CONTENIDO.CLSETIQUETA4.Name = "CLSETIQUETA4"
CONTENIDO.SEL_ARTICULO.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.SEL_ARTICULO.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.SEL_ARTICULO.Name = "SEL_ARTICULO"
CONTENIDO.CLSETIQUETA5.Name = "CLSETIQUETA5"
CONTENIDO.TXTCANTIDAD.Name = "TXTCANTIDAD"
CONTENIDO.BTNAGREGAR.Name = "BTNAGREGAR"
CONTENIDO.GRDDETALLES.Column1.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.Column1.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.Column1.Name = "Column1"
CONTENIDO.GRDDETALLES.Column2.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.Column2.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.Column2.Name = "Column2"
CONTENIDO.GRDDETALLES.Column3.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.Column3.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.Column3.Name = "Column3"
CONTENIDO.GRDDETALLES.COLUMN4.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN4.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN4.Name = "COLUMN4"
CONTENIDO.GRDDETALLES.COLUMN5.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN5.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN5.Name = "COLUMN5"
CONTENIDO.GRDDETALLES.COLUMN6.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN6.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN6.Name = "COLUMN6"
CONTENIDO.GRDDETALLES.COLUMN7.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN7.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN7.Name = "COLUMN7"
CONTENIDO.GRDDETALLES.COLUMN8.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN8.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN8.Name = "COLUMN8"
CONTENIDO.GRDDETALLES.COLUMN9.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN9.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN9.Name = "COLUMN9"
CONTENIDO.GRDDETALLES.COLUMN10.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN10.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN10.Name = "COLUMN10"
CONTENIDO.GRDDETALLES.COLUMN11.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN11.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN11.Name = "COLUMN11"
CONTENIDO.GRDDETALLES.COLUMN12.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN12.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN12.Name = "COLUMN12"
CONTENIDO.GRDDETALLES.COLUMN13.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN13.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN13.Name = "COLUMN13"
CONTENIDO.GRDDETALLES.COLUMN14.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN14.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN14.Name = "COLUMN14"
CONTENIDO.GRDDETALLES.COLUMN15.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN15.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN15.Name = "COLUMN15"
CONTENIDO.GRDDETALLES.COLUMN16.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN16.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN16.Name = "COLUMN16"
CONTENIDO.GRDDETALLES.COLUMN17.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN17.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN17.Name = "COLUMN17"
CONTENIDO.GRDDETALLES.COLUMN18.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN18.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN18.Name = "COLUMN18"
CONTENIDO.GRDDETALLES.COLUMN19.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN19.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN19.Name = "COLUMN19"
CONTENIDO.GRDDETALLES.COLUMN20.Header1.Name = "Header1"
CONTENIDO.GRDDETALLES.COLUMN20.Text1.Name = "Text1"
CONTENIDO.GRDDETALLES.COLUMN20.Name = "COLUMN20"
CONTENIDO.GRDDETALLES.Name = "GRDDETALLES"
CONTENIDO.BTNGRABAR.Name = "BTNGRABAR"
CONTENIDO.BTNCANCELAR.Name = "BTNCANCELAR"
CONTENIDO.CLSCERRAR1.Name = "CLSCERRAR1"
CONTENIDO.CLSETIQUETA10.Name = "CLSETIQUETA10"
CONTENIDO.TXTPRMAY.Name = "TXTPRMAY"
CONTENIDO.CLSETIQUETA11.Name = "CLSETIQUETA11"
CONTENIDO.TXTPRMINORISTA.Name = "TXTPRMINORISTA"
CONTENIDO.CLSETIQUETA12.Name = "CLSETIQUETA12"
CONTENIDO.TXTALICIVA.Name = "TXTALICIVA"
CONTENIDO.CHKCALCIVA.Alignment = 0
CONTENIDO.CHKCALCIVA.Name = "CHKCALCIVA"
CONTENIDO.BTNELIMINAR.Name = "BTNELIMINAR"
CONTENIDO.CHKIMPRIMEDUP.Alignment = 0
CONTENIDO.CHKIMPRIMEDUP.Name = "CHKIMPRIMEDUP"
CONTENIDO.BTNCBTEORIGEN.Name = "BTNCBTEORIGEN"
CONTENIDO.TXTOBSERV.Name = "TXTOBSERV"
CONTENIDO.CLSETIQUETA6.Name = "CLSETIQUETA6"
CONTENIDO.CLSETIQUETA7.Name = "CLSETIQUETA7"
CONTENIDO.CLSETIQUETA8.Name = "CLSETIQUETA8"
CONTENIDO.CLSETIQUETA9.Name = "CLSETIQUETA9"
CONTENIDO.TXTTOTNETO.Name = "TXTTOTNETO"
CONTENIDO.TXTPORIVA21.Name = "TXTPORIVA21"
CONTENIDO.TXTPORIVA105.Name = "TXTPORIVA105"
CONTENIDO.TXTIMPIVA21.Name = "TXTIMPIVA21"
CONTENIDO.TXTIMPIVA105.Name = "TXTIMPIVA105"
CONTENIDO.TXTTOTAL.Name = "TXTTOTAL"
CONTENIDO.CLSETIQUETA14.Name = "CLSETIQUETA14"
CONTENIDO.TXTDESC1.Name = "TXTDESC1"
CONTENIDO.TXTDESC2.Name = "TXTDESC2"
CONTENIDO.TXTDESC3.Name = "TXTDESC3"
CONTENIDO.TXTDESC4.Name = "TXTDESC4"
CONTENIDO.TXTIMPDESC1.Name = "TXTIMPDESC1"
CONTENIDO.TXTIMPDESC2.Name = "TXTIMPDESC2"
CONTENIDO.TXTIMPDESC3.Name = "TXTIMPDESC3"
CONTENIDO.TXTIMPDESC4.Name = "TXTIMPDESC4"
CONTENIDO.CLSETIQUETA15.Name = "CLSETIQUETA15"
CONTENIDO.CLSETIQUETA16.Name = "CLSETIQUETA16"
CONTENIDO.CLSETIQUETA17.Name = "CLSETIQUETA17"
CONTENIDO.TXTTOTFACT.Name = "TXTTOTFACT"
CONTENIDO.CLSETIQUETA18.Name = "CLSETIQUETA18"
CONTENIDO.TXTPORIIBB.Name = "TXTPORIIBB"
CONTENIDO.TXTIMPIIBB.Name = "TXTIMPIIBB"
CONTENIDO.Clsetiqueta19.Name = "Clsetiqueta19"
CONTENIDO.txtST.Name = "txtST"
CONTENIDO.Clsetiqueta20.Name = "Clsetiqueta20"
CONTENIDO.txtPorDesc1.Name = "txtPorDesc1"
CONTENIDO.txtImpDescItem1.Name = "txtImpDescItem1"
CONTENIDO.txtPorDesc2.Name = "txtPorDesc2"
CONTENIDO.txtImpDescItem2.Name = "txtImpDescItem2"
CONTENIDO.txtPorDesc3.Name = "txtPorDesc3"
CONTENIDO.txtImpDescItem3.Name = "txtImpDescItem3"
CONTENIDO.txtPorDesc4.Name = "txtPorDesc4"
CONTENIDO.txtImpDescItem4.Name = "txtImpDescItem4"
CONTENIDO.Clsetiqueta21.Name = "Clsetiqueta21"
CONTENIDO.txtImpIVA.Name = "txtImpIVA"
CONTENIDO.Clsetiqueta22.Name = "Clsetiqueta22"
CONTENIDO.txtSTNeto.Name = "txtSTNeto"
CONTENIDO.CLSETIQUETA13.Name = "CLSETIQUETA13"
CONTENIDO.TXTSUBTOTAL.Name = "TXTSUBTOTAL"
CONTENIDO.Clsetiqueta23.Name = "Clsetiqueta23"
CONTENIDO.txtPrNeto.Name = "txtPrNeto"
CONTENIDO.lblExistencia.Name = "lblExistencia"
CONTENIDO.txtExistencia.Name = "txtExistencia"
CONTENIDO.Name = "CONTENIDO"
mov_stock.Name = "mov_stock"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0
Arial, 1, 9, 6, 15, 12, 32, 3, 0

*** METODOS ***


