************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmconsulta_oc
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frmconsulta_oc"
Contenedor1.Clsetiqueta3.Name = "Clsetiqueta3"
Contenedor1.Clsetiqueta4.Name = "Clsetiqueta4"
Contenedor1.txtOcDesde.Name = "txtOcDesde"
Contenedor1.txtOcHasta.Name = "txtOcHasta"
Contenedor1.btnSalir.Name = "btnSalir"
Contenedor1.btnBuscar.Name = "btnBuscar"
Contenedor1.Clsetiqueta1.Name = "Clsetiqueta1"
Contenedor1.grdDet.COLUMN1.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN1.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN1.Name = "COLUMN1"
Contenedor1.grdDet.COLUMN2.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN2.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN2.Name = "COLUMN2"
Contenedor1.grdDet.COLUMN3.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN3.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN3.Name = "COLUMN3"
Contenedor1.grdDet.COLUMN4.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN4.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN4.Name = "COLUMN4"
Contenedor1.grdDet.COLUMN5.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN5.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN5.Name = "COLUMN5"
Contenedor1.grdDet.COLUMN6.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN6.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN6.Name = "COLUMN6"
Contenedor1.grdDet.COLUMN7.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN7.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN7.Name = "COLUMN7"
Contenedor1.grdDet.COLUMN8.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN8.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN8.Name = "COLUMN8"
Contenedor1.grdDet.COLUMN9.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN9.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN9.chkactivo.Alignment = 0
Contenedor1.grdDet.COLUMN9.chkactivo.Name = "chkactivo"
Contenedor1.grdDet.COLUMN9.Name = "COLUMN9"
Contenedor1.grdDet.COLUMN10.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN10.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN10.Name = "COLUMN10"
Contenedor1.grdDet.COLUMN11.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN11.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN11.Name = "COLUMN11"
Contenedor1.grdDet.COLUMN12.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN12.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN12.Name = "COLUMN12"
Contenedor1.grdDet.COLUMN13.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN13.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN13.Name = "COLUMN13"
Contenedor1.grdDet.COLUMN14.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN14.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN14.Name = "COLUMN14"
Contenedor1.grdDet.COLUMN15.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN15.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN15.Name = "COLUMN15"
Contenedor1.grdDet.COLUMN16.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN16.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN16.Name = "COLUMN16"
Contenedor1.grdDet.COLUMN17.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN17.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN17.Name = "COLUMN17"
Contenedor1.grdDet.COLUMN18.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN18.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN18.Name = "COLUMN18"
Contenedor1.grdDet.COLUMN19.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN19.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN19.Name = "COLUMN19"
Contenedor1.grdDet.COLUMN20.Header1.Name = "Header1"
Contenedor1.grdDet.COLUMN20.Text1.Name = "Text1"
Contenedor1.grdDet.COLUMN20.Name = "COLUMN20"
Contenedor1.grdDet.Name = "grdDet"
Contenedor1.sel_prov_desde.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_prov_desde.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_prov_desde.Name = "sel_prov_desde"
Contenedor1.sel_prov_hasta.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_prov_hasta.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_prov_hasta.Name = "sel_prov_hasta"
Contenedor1.Clsetiqueta2.Name = "Clsetiqueta2"
Contenedor1.Clsetiqueta8.Name = "Clsetiqueta8"
Contenedor1.Clsimprimir1.Name = "Clsimprimir1"
Contenedor1.Clscancelar1.Name = "Clscancelar1"
Contenedor1.Clsetiqueta5.Name = "Clsetiqueta5"
Contenedor1.Clsetiqueta6.Name = "Clsetiqueta6"
Contenedor1.txtFecDesde.Name = "txtFecDesde"
Contenedor1.txtFecHasta.Name = "txtFecHasta"
Contenedor1.sel_marca_desde.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_marca_desde.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_marca_desde.Name = "sel_marca_desde"
Contenedor1.sel_marca_hasta.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_marca_hasta.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_marca_hasta.Name = "sel_marca_hasta"
Contenedor1.Clsetiqueta7.Name = "Clsetiqueta7"
Contenedor1.Clsetiqueta9.Name = "Clsetiqueta9"
Contenedor1.chkEntreg.Alignment = 0
Contenedor1.chkEntreg.Name = "chkEntreg"
Contenedor1.grdCab.COLUMN1.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN1.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN1.Name = "COLUMN1"
Contenedor1.grdCab.COLUMN2.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN2.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN2.Name = "COLUMN2"
Contenedor1.grdCab.COLUMN3.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN3.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN3.Name = "COLUMN3"
Contenedor1.grdCab.COLUMN4.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN4.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN4.Name = "COLUMN4"
Contenedor1.grdCab.COLUMN5.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN5.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN5.Name = "COLUMN5"
Contenedor1.grdCab.COLUMN6.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN6.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN6.Name = "COLUMN6"
Contenedor1.grdCab.COLUMN7.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN7.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN7.Name = "COLUMN7"
Contenedor1.grdCab.COLUMN8.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN8.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN8.Name = "COLUMN8"
Contenedor1.grdCab.COLUMN9.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN9.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN9.chkent.Alignment = 0
Contenedor1.grdCab.COLUMN9.chkent.Name = "chkent"
Contenedor1.grdCab.COLUMN9.Name = "COLUMN9"
Contenedor1.grdCab.COLUMN10.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN10.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN10.Name = "COLUMN10"
Contenedor1.grdCab.COLUMN11.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN11.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN11.Name = "COLUMN11"
Contenedor1.grdCab.COLUMN12.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN12.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN12.Name = "COLUMN12"
Contenedor1.grdCab.COLUMN13.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN13.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN13.Name = "COLUMN13"
Contenedor1.grdCab.COLUMN14.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN14.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN14.Name = "COLUMN14"
Contenedor1.grdCab.COLUMN15.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN15.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN15.Name = "COLUMN15"
Contenedor1.grdCab.COLUMN16.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN16.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN16.Name = "COLUMN16"
Contenedor1.grdCab.COLUMN17.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN17.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN17.Name = "COLUMN17"
Contenedor1.grdCab.COLUMN18.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN18.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN18.Name = "COLUMN18"
Contenedor1.grdCab.COLUMN19.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN19.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN19.Name = "COLUMN19"
Contenedor1.grdCab.COLUMN20.Header1.Name = "Header1"
Contenedor1.grdCab.COLUMN20.Text1.Name = "Text1"
Contenedor1.grdCab.COLUMN20.Name = "COLUMN20"
Contenedor1.grdCab.Name = "grdCab"
Contenedor1.Name = "Contenedor1"
oc.Name = "oc"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0

*** METODOS ***


