************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmplanif_cpr
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frmplanif_cpr"
contenido.Pages.ErasePage = .T.
contenido.Pages.Page1.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.Pages.Page1.selProveedor.txtCodigo.Name = "txtCodigo"
contenido.Pages.Page1.selProveedor.txtDescripcion.Name = "txtDescripcion"
contenido.Pages.Page1.selProveedor.Name = "selProveedor"
contenido.Pages.Page1.grdSubRubros.COLUMN1.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN1.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN1.CLSCHECKBOX1.Alignment = 0
contenido.Pages.Page1.grdSubRubros.COLUMN1.CLSCHECKBOX1.Name = "CLSCHECKBOX1"
contenido.Pages.Page1.grdSubRubros.COLUMN1.Name = "COLUMN1"
contenido.Pages.Page1.grdSubRubros.COLUMN2.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN2.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN2.Name = "COLUMN2"
contenido.Pages.Page1.grdSubRubros.COLUMN3.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN3.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN3.Name = "COLUMN3"
contenido.Pages.Page1.grdSubRubros.COLUMN4.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN4.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN4.Name = "COLUMN4"
contenido.Pages.Page1.grdSubRubros.COLUMN5.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN5.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN5.Name = "COLUMN5"
contenido.Pages.Page1.grdSubRubros.COLUMN6.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN6.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN6.Name = "COLUMN6"
contenido.Pages.Page1.grdSubRubros.COLUMN7.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN7.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN7.Name = "COLUMN7"
contenido.Pages.Page1.grdSubRubros.COLUMN8.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN8.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN8.Name = "COLUMN8"
contenido.Pages.Page1.grdSubRubros.COLUMN9.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN9.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN9.Name = "COLUMN9"
contenido.Pages.Page1.grdSubRubros.COLUMN10.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN10.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN10.Name = "COLUMN10"
contenido.Pages.Page1.grdSubRubros.COLUMN11.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN11.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN11.Name = "COLUMN11"
contenido.Pages.Page1.grdSubRubros.COLUMN12.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN12.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN12.Name = "COLUMN12"
contenido.Pages.Page1.grdSubRubros.COLUMN13.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN13.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN13.Name = "COLUMN13"
contenido.Pages.Page1.grdSubRubros.COLUMN14.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN14.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN14.Name = "COLUMN14"
contenido.Pages.Page1.grdSubRubros.COLUMN15.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN15.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN15.Name = "COLUMN15"
contenido.Pages.Page1.grdSubRubros.COLUMN16.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN16.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN16.Name = "COLUMN16"
contenido.Pages.Page1.grdSubRubros.COLUMN17.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN17.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN17.Name = "COLUMN17"
contenido.Pages.Page1.grdSubRubros.COLUMN18.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN18.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN18.Name = "COLUMN18"
contenido.Pages.Page1.grdSubRubros.COLUMN19.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN19.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN19.Name = "COLUMN19"
contenido.Pages.Page1.grdSubRubros.COLUMN20.Header1.Name = "Header1"
contenido.Pages.Page1.grdSubRubros.COLUMN20.Text1.Name = "Text1"
contenido.Pages.Page1.grdSubRubros.COLUMN20.Name = "COLUMN20"
contenido.Pages.Page1.grdSubRubros.Name = "grdSubRubros"
contenido.Pages.Page1.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.Pages.Page1.chkTodos.Alignment = 0
contenido.Pages.Page1.chkTodos.Name = "chkTodos"
contenido.Pages.Page1.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.Pages.Page1.Clsetiqueta4.Name = "Clsetiqueta4"
contenido.Pages.Page1.Clsetiqueta5.Name = "Clsetiqueta5"
contenido.Pages.Page1.txtFecDesde.Name = "txtFecDesde"
contenido.Pages.Page1.txtFecHasta.Name = "txtFecHasta"
contenido.Pages.Page1.chkBaseCalc.Alignment = 0
contenido.Pages.Page1.chkBaseCalc.Name = "chkBaseCalc"
contenido.Pages.Page1.Clslinea1.Name = "Clslinea1"
contenido.Pages.Page1.btnAceptar.Name = "btnAceptar"
contenido.Pages.Page1.Clsetiqueta6.Name = "Clsetiqueta6"
contenido.Pages.Page1.sel_marca.txtCodigo.Name = "txtCodigo"
contenido.Pages.Page1.sel_marca.txtDescripcion.Name = "txtDescripcion"
contenido.Pages.Page1.sel_marca.Name = "sel_marca"
contenido.Pages.Page1.btnBuscar.Name = "btnBuscar"
contenido.Pages.Page1.Clsetiqueta7.Name = "Clsetiqueta7"
contenido.Pages.Page1.txtFecEnt.Name = "txtFecEnt"
contenido.Pages.Page1.Name = "Page1"
contenido.Pages.Page2.grdPlanificar.COLUMN1.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN1.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN1.Name = "COLUMN1"
contenido.Pages.Page2.grdPlanificar.COLUMN2.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN2.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN2.Name = "COLUMN2"
contenido.Pages.Page2.grdPlanificar.COLUMN3.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN3.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN3.Name = "COLUMN3"
contenido.Pages.Page2.grdPlanificar.COLUMN4.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN4.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN4.Name = "COLUMN4"
contenido.Pages.Page2.grdPlanificar.COLUMN5.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN5.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN5.Name = "COLUMN5"
contenido.Pages.Page2.grdPlanificar.COLUMN6.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN6.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN6.Name = "COLUMN6"
contenido.Pages.Page2.grdPlanificar.COLUMN7.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN7.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN7.Name = "COLUMN7"
contenido.Pages.Page2.grdPlanificar.COLUMN8.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN8.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN8.Name = "COLUMN8"
contenido.Pages.Page2.grdPlanificar.COLUMN9.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN9.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN9.Name = "COLUMN9"
contenido.Pages.Page2.grdPlanificar.COLUMN10.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN10.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN10.Name = "COLUMN10"
contenido.Pages.Page2.grdPlanificar.COLUMN11.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN11.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN11.Name = "COLUMN11"
contenido.Pages.Page2.grdPlanificar.COLUMN12.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN12.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN12.Name = "COLUMN12"
contenido.Pages.Page2.grdPlanificar.COLUMN13.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN13.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN13.Name = "COLUMN13"
contenido.Pages.Page2.grdPlanificar.COLUMN14.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN14.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN14.Name = "COLUMN14"
contenido.Pages.Page2.grdPlanificar.COLUMN15.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN15.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN15.Name = "COLUMN15"
contenido.Pages.Page2.grdPlanificar.COLUMN16.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN16.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN16.Name = "COLUMN16"
contenido.Pages.Page2.grdPlanificar.COLUMN17.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN17.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN17.Name = "COLUMN17"
contenido.Pages.Page2.grdPlanificar.COLUMN18.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN18.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN18.Name = "COLUMN18"
contenido.Pages.Page2.grdPlanificar.COLUMN19.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN19.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN19.Name = "COLUMN19"
contenido.Pages.Page2.grdPlanificar.COLUMN20.Header1.Name = "Header1"
contenido.Pages.Page2.grdPlanificar.COLUMN20.Text1.Name = "Text1"
contenido.Pages.Page2.grdPlanificar.COLUMN20.Name = "COLUMN20"
contenido.Pages.Page2.grdPlanificar.Name = "grdPlanificar"
contenido.Pages.Page2.btnDetaEstad.Name = "btnDetaEstad"
contenido.Pages.Page2.btnMovStock.Name = "btnMovStock"
contenido.Pages.Page2.btnDetalVtas.Name = "btnDetalVtas"
contenido.Pages.Page2.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.Pages.Page2.txtTotPed.Name = "txtTotPed"
contenido.Pages.Page2.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.Pages.Page2.txtTotCosto.Name = "txtTotCosto"
contenido.Pages.Page2.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.Pages.Page2.txtObsev.Name = "txtObsev"
contenido.Pages.Page2.Clsgenerico1.Name = "Clsgenerico1"
contenido.Pages.Page2.Name = "Page2"
contenido.Pages.Name = "Pages"
contenido.Name = "contenido"
btnCerrar.Name = "btnCerrar"
planificacion.Name = "planificacion"
btnCancelar.Name = "btnCancelar"
btnGrabar.Name = "btnGrabar"
Clsexcel1.Name = "Clsexcel1"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


