************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_abm_motrec
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_abm_motrec"
HERRAMIENTAS.CMDNUEVO.Name = "CMDNUEVO"
HERRAMIENTAS.CMDEDITAR.Name = "CMDEDITAR"
HERRAMIENTAS.CMDELIMINAR.Name = "CMDELIMINAR"
HERRAMIENTAS.CMDCERRAR.Name = "CMDCERRAR"
HERRAMIENTAS.CMDGRABAR.Name = "CMDGRABAR"
HERRAMIENTAS.CMDCANCELAR.Name = "CMDCANCELAR"
HERRAMIENTAS.CMDEXCEL.Name = "CMDEXCEL"
HERRAMIENTAS.Name = "HERRAMIENTAS"
PGF.ErasePage = .T.
PGF.PAGE1.GRDDATOS.COLUMN1.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN1.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN1.Name = "COLUMN1"
PGF.PAGE1.GRDDATOS.COLUMN2.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN2.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN2.Name = "COLUMN2"
PGF.PAGE1.GRDDATOS.COLUMN3.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN3.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN3.Name = "COLUMN3"
PGF.PAGE1.GRDDATOS.COLUMN4.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN4.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN4.Name = "COLUMN4"
PGF.PAGE1.GRDDATOS.COLUMN5.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN5.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN5.Name = "COLUMN5"
PGF.PAGE1.GRDDATOS.COLUMN6.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN6.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN6.Name = "COLUMN6"
PGF.PAGE1.GRDDATOS.COLUMN7.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN7.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN7.Name = "COLUMN7"
PGF.PAGE1.GRDDATOS.COLUMN8.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN8.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN8.Name = "COLUMN8"
PGF.PAGE1.GRDDATOS.COLUMN9.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN9.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN9.Name = "COLUMN9"
PGF.PAGE1.GRDDATOS.COLUMN10.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN10.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN10.Name = "COLUMN10"
PGF.PAGE1.GRDDATOS.COLUMN11.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN11.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN11.Name = "COLUMN11"
PGF.PAGE1.GRDDATOS.COLUMN12.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN12.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN12.Name = "COLUMN12"
PGF.PAGE1.GRDDATOS.COLUMN13.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN13.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN13.Name = "COLUMN13"
PGF.PAGE1.GRDDATOS.COLUMN14.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN14.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN14.Name = "COLUMN14"
PGF.PAGE1.GRDDATOS.COLUMN15.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN15.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN15.Name = "COLUMN15"
PGF.PAGE1.GRDDATOS.COLUMN16.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN16.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN16.Name = "COLUMN16"
PGF.PAGE1.GRDDATOS.COLUMN17.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN17.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN17.Name = "COLUMN17"
PGF.PAGE1.GRDDATOS.COLUMN18.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN18.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN18.Name = "COLUMN18"
PGF.PAGE1.GRDDATOS.COLUMN19.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN19.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN19.Name = "COLUMN19"
PGF.PAGE1.GRDDATOS.COLUMN20.Header1.Name = "Header1"
PGF.PAGE1.GRDDATOS.COLUMN20.Text1.Name = "Text1"
PGF.PAGE1.GRDDATOS.COLUMN20.Name = "COLUMN20"
PGF.PAGE1.GRDDATOS.Name = "GRDDATOS"
PGF.PAGE1.Name = "PAGE1"
PGF.PAGE2.CNT_FIELDS.CLSETIQUETA1.Name = "CLSETIQUETA1"
PGF.PAGE2.CNT_FIELDS.txt_descripcion.Name = "txt_descripcion"
PGF.PAGE2.CNT_FIELDS.Name = "CNT_FIELDS"
PGF.PAGE2.Name = "PAGE2"
PGF.Name = "PGF"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


