************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_rcn_abm_operadores
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Caption = "ABM Lista de operadores"
Name = "frm_rcn_abm_operadores"
HERRAMIENTAS.CMDNUEVO.Name = "CMDNUEVO"
HERRAMIENTAS.CMDEDITAR.Name = "CMDEDITAR"
HERRAMIENTAS.CMDELIMINAR.Name = "CMDELIMINAR"
HERRAMIENTAS.CMDCERRAR.Name = "CMDCERRAR"
HERRAMIENTAS.CMDGRABAR.Name = "CMDGRABAR"
HERRAMIENTAS.CMDCANCELAR.Name = "CMDCANCELAR"
HERRAMIENTAS.CMDEXCEL.Name = "CMDEXCEL"
HERRAMIENTAS.Name = "HERRAMIENTAS"
PGF.ErasePage = .T.
PGF.PAGE1.GRDDATOS.COLUMN1.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN1.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN1.Name = "COLUMN1"
PGF.PAGE1.GRDDATOS.COLUMN2.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN2.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN2.Name = "COLUMN2"
PGF.PAGE1.GRDDATOS.COLUMN3.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN3.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN3.Name = "COLUMN3"
PGF.PAGE1.GRDDATOS.COLUMN4.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN4.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN4.Name = "COLUMN4"
PGF.PAGE1.GRDDATOS.COLUMN5.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN5.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN5.Name = "COLUMN5"
PGF.PAGE1.GRDDATOS.COLUMN6.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN6.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN6.Name = "COLUMN6"
PGF.PAGE1.GRDDATOS.COLUMN7.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN7.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN7.Name = "COLUMN7"
PGF.PAGE1.GRDDATOS.COLUMN8.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN8.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN8.Name = "COLUMN8"
PGF.PAGE1.GRDDATOS.COLUMN9.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN9.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN9.Name = "COLUMN9"
PGF.PAGE1.GRDDATOS.COLUMN10.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN10.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN10.Name = "COLUMN10"
PGF.PAGE1.GRDDATOS.COLUMN11.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN11.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN11.Name = "COLUMN11"
PGF.PAGE1.GRDDATOS.COLUMN12.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN12.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN12.Name = "COLUMN12"
PGF.PAGE1.GRDDATOS.COLUMN13.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN13.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN13.Name = "COLUMN13"
PGF.PAGE1.GRDDATOS.COLUMN14.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN14.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN14.Name = "COLUMN14"
PGF.PAGE1.GRDDATOS.COLUMN15.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN15.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN15.Name = "COLUMN15"
PGF.PAGE1.GRDDATOS.COLUMN16.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN16.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN16.Name = "COLUMN16"
PGF.PAGE1.GRDDATOS.COLUMN17.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN17.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN17.Name = "COLUMN17"
PGF.PAGE1.GRDDATOS.COLUMN18.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN18.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN18.Name = "COLUMN18"
PGF.PAGE1.GRDDATOS.COLUMN19.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN19.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN19.Name = "COLUMN19"
PGF.PAGE1.GRDDATOS.COLUMN20.HEADER1.Name = "HEADER1"
PGF.PAGE1.GRDDATOS.COLUMN20.TEXT1.Name = "TEXT1"
PGF.PAGE1.GRDDATOS.COLUMN20.Name = "COLUMN20"
PGF.PAGE1.GRDDATOS.Name = "GRDDATOS"
PGF.PAGE1.Name = "PAGE1"
PGF.PAGE2.CNT_FIELDS.Name = "CNT_FIELDS"
PGF.PAGE2.Name = "PAGE2"
PGF.Name = "PGF"

*** METODOS ***


************************************************************
OBJETO: TXTAPELNOM
************************************************************
*** PROPIEDADES ***
Height = 24
Left = 152
Top = 23
Width = 524
ischaracter = .T.
cfieldname = apelnom
Name = "TXTAPELNOM"

*** METODOS ***


************************************************************
OBJETO: CLSETIQUETA1
************************************************************
*** PROPIEDADES ***
Caption = "Apellido y nombre:"
Height = 24
Left = 24
Top = 27
Width = 132
Name = "CLSETIQUETA1"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


