************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_rcn_ingreso_remitos
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_rcn_ingreso_remitos"
CONTENIDO.cnt_cabecera.SEL_CLIENTE.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.cnt_cabecera.SEL_CLIENTE.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.cnt_cabecera.SEL_CLIENTE.Name = "SEL_CLIENTE"
CONTENIDO.cnt_cabecera.CLSETIQUETA1.Name = "CLSETIQUETA1"
CONTENIDO.cnt_cabecera.CLSETIQUETA2.Name = "CLSETIQUETA2"
CONTENIDO.cnt_cabecera.txt_numero_remito.Name = "txt_numero_remito"
CONTENIDO.cnt_cabecera.CLSETIQUETA3.Name = "CLSETIQUETA3"
CONTENIDO.cnt_cabecera.txt_destino.Name = "txt_destino"
CONTENIDO.cnt_cabecera.BTNACEPTAR.Name = "BTNACEPTAR"
CONTENIDO.cnt_cabecera.BTNCANCELAR.Name = "BTNCANCELAR"
CONTENIDO.cnt_cabecera.CLSETIQUETA4.Name = "CLSETIQUETA4"
CONTENIDO.cnt_cabecera.Name = "cnt_cabecera"
CONTENIDO.CNT_ITEMS.CLSETIQUETA4.Name = "CLSETIQUETA4"
CONTENIDO.CNT_ITEMS.CLSETIQUETA1.Name = "CLSETIQUETA1"
CONTENIDO.CNT_ITEMS.sel_marcas.TXTCODIGO.Name = "TXTCODIGO"
CONTENIDO.CNT_ITEMS.sel_marcas.TXTDESCRIPCION.Name = "TXTDESCRIPCION"
CONTENIDO.CNT_ITEMS.sel_marcas.Name = "sel_marcas"
CONTENIDO.CNT_ITEMS.CLSETIQUETA2.Name = "CLSETIQUETA2"
CONTENIDO.CNT_ITEMS.txt_medida.Name = "txt_medida"
CONTENIDO.CNT_ITEMS.CLSETIQUETA3.Name = "CLSETIQUETA3"
CONTENIDO.CNT_ITEMS.txt_nro_serie.Name = "txt_nro_serie"
CONTENIDO.CNT_ITEMS.CLSETIQUETA5.Name = "CLSETIQUETA5"
CONTENIDO.CNT_ITEMS.txt_trabajo_a_realizar.Name = "txt_trabajo_a_realizar"
CONTENIDO.CNT_ITEMS.BTNAGREGAR.Name = "BTNAGREGAR"
CONTENIDO.CNT_ITEMS.BTNELIMINAR.Name = "BTNELIMINAR"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN1.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN1.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN1.Name = "COLUMN1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN2.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN2.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN2.Name = "COLUMN2"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN3.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN3.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN3.Name = "COLUMN3"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN4.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN4.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN4.Name = "COLUMN4"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN5.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN5.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN5.Name = "COLUMN5"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN6.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN6.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN6.Name = "COLUMN6"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN7.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN7.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN7.Name = "COLUMN7"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN8.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN8.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN8.Name = "COLUMN8"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN9.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN9.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN9.Name = "COLUMN9"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN10.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN10.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN10.Name = "COLUMN10"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN11.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN11.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN11.Name = "COLUMN11"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN12.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN12.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN12.Name = "COLUMN12"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN13.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN13.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN13.Name = "COLUMN13"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN14.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN14.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN14.Name = "COLUMN14"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN15.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN15.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN15.Name = "COLUMN15"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN16.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN16.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN16.Name = "COLUMN16"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN17.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN17.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN17.Name = "COLUMN17"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN18.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN18.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN18.Name = "COLUMN18"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN19.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN19.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN19.Name = "COLUMN19"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN20.HEADER1.Name = "HEADER1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN20.TEXT1.Name = "TEXT1"
CONTENIDO.CNT_ITEMS.grd_items.COLUMN20.Name = "COLUMN20"
CONTENIDO.CNT_ITEMS.grd_items.Name = "grd_items"
CONTENIDO.CNT_ITEMS.Name = "CNT_ITEMS"
CONTENIDO.CLSETIQUETA1.Name = "CLSETIQUETA1"
CONTENIDO.txt_observaciones.Name = "txt_observaciones"
CONTENIDO.btn_nuevo.Name = "btn_nuevo"
CONTENIDO.btn_grabar.Name = "btn_grabar"
CONTENIDO.CLSCERRAR1.Name = "CLSCERRAR1"
CONTENIDO.Name = "CONTENIDO"
oRemitosDal.Name = "oRemitosDal"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


