CREATE PROCEDURE ventasdet_temp_insert (
	xidArticulo int,
	xcantidad decimal(20, 2),
	xcantNC decimal(20, 2),
	xcostoRep decimal(20, 2),
	xprArtic decimal(20, 2),
	xprVenta decimal(20, 2),
	xporDesc1 decimal(5, 2),
	xporDesc2 decimal(5, 2),
	xporDesc3 decimal(5, 2),
	xporDesc4 decimal(5, 2),
	ximpDesc1 decimal(20, 2),
	ximpDesc2 decimal(20, 2),
	ximpDesc3 decimal(20, 2),
	ximpDesc4 decimal(20, 2),
	xpDtoVta1 decimal(5, 2),
	xpDtoVta2 decimal(5, 2),
	xpDtoVta3 decimal(5, 2),
	xpDtoVta4 decimal(5, 2),
	xiDtoVta1 decimal(20, 2),
	xiDtoVta2 decimal(20, 2),
	xiDtoVta3 decimal(20, 2),
	xiDtoVta4 decimal(20, 2),
	ximpNeto decimal(20, 2),
	xporNoGrav decimal(20, 2),
	xbaseGrav decimal(20, 2),
	xsubtNoGrav decimal(20, 2),
	xtotNeto decimal(20, 2),
	xalicIVA decimal(5, 2),
	ximpIVA decimal(20, 2),
	xsubTotal decimal(20, 2),
	xnroPart varchar(30),
	xesOferta bit,
	xpRecVta decimal(5, 2),
	xiRecVta decimal(20, 2),
	xUniDesp decimal(20, 2),
	xcantPack decimal(20, 2),
	xcodUM varchar(3),
	xcant_pri1 decimal(20, 2),
	xcant_pri2 decimal(20, 2),
	xcant_pri3 decimal(20, 2),
	xdescripcio varchar(200),
	xcant_falt decimal(20, 2),
	xpRecItem decimal(5, 2),
	xiRecItem decimal(5, 2),
	xusuario varchar(5),
	xhost varchar(50)
)
BEGIN
	DECLARE vMensaje TEXT;
	DECLARE EXIT handler FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 vMensaje = MESSAGE_TEXT;
		INSERT INTO log_sps (sp_name, msgerror, usuario, host)
		VALUES ('ventasdet_temp_insert', vMensaje, xusuario, xhost);
		SELECT 0 AS 'result';
	END;

	INSERT INTO ventasdet_tmp (
		idArticulo,
		cantidad,
		cantNC,
		costoRep,
		prArtic,
		prVenta,
		porDesc1,
		porDesc2,
		porDesc3,
		porDesc4,
		impDesc1,
		impDesc2,
		impDesc3,
		impDesc4,
		pDtoVta1,
		pDtoVta2,
		pDtoVta3,
		pDtoVta4,
		iDtoVta1,
		iDtoVta2,
		iDtoVta3,
		iDtoVta4,
		impNeto,
		porNoGrav,
		baseGrav,
		subtNoGrav,
		totNeto,
		alicIVA,
		impIVA,
		subTotal,
		nroPart,
		esOferta,
		pRecVta,
		iRecVta,
		UniDesp,
		cantPack,
		codUM,
		cant_pri1,
		cant_pri2,
		cant_pri3,
		descripcio,
		cant_falt,
		pRecItem,
		iRecItem,
		usuario,
		host)
	VALUES (
		xidArticulo,
		xcantidad,
		xcantNC,
		xcostoRep,
		xprArtic,
		xprVenta,
		xporDesc1,
		xporDesc2,
		xporDesc3,
		xporDesc4,
		ximpDesc1,
		ximpDesc2,
		ximpDesc3,
		ximpDesc4,
		xpDtoVta1,
		xpDtoVta2,
		xpDtoVta3,
		xpDtoVta4,
		xiDtoVta1,
		xiDtoVta2,
		xiDtoVta3,
		xiDtoVta4,
		ximpNeto,
		xporNoGrav,
		xbaseGrav,
		xsubtNoGrav,
		xtotNeto,
		xalicIVA,
		ximpIVA,
		xsubTotal,
		xnroPart,
		xesOferta,
		xpRecVta,
		xiRecVta,
		xUniDesp,
		xcantPack,
		xcodUM,
		xcant_pri1,
		xcant_pri2,
		xcant_pri3,
		xdescripcio,
		xcant_falt,
		xpRecItem,
		xiRecItem,
		xusuario,
		xhost);

	SELECT 1 AS 'result';
END