CREATE PROCEDURE ventas_generar_cbtes (
	xidCliente	int(11),
	xidCondPago	int(11),
	xidSitIVA	int(11),
	xidVendedor	int(11),
	xfecEmision	datetime,
	xfecVto		datetime,
	xcbte		varchar(3),
	xtipoDoc	varchar(1),
	xptoVta		int(11),
	xnumCbte	int(11),
	ximpNeto	decimal(20, 2),
	ximpFinal	decimal(20, 2),
	xporIVA21	decimal(5, 2),
	ximpIVA21	decimal(20, 2),
	xporIVA105	decimal(5, 2),
	ximpIVA105	decimal(20, 2),
	xporIIBB	decimal(5, 2),
	ximpIIBB	decimal(20, 2),
	xporDesc1	decimal(5, 2),
	ximpDesc1	decimal(20, 2),
	xporDesc2	decimal(5, 2),
	ximpDesc2	decimal(20, 2),
	xporDesc3	decimal(5, 2),
	ximpDesc3	decimal(20, 2),
	xporDesc4	decimal(5, 2),
	ximpDesc4	decimal(20, 2),
	xporRec		decimal(5, 2),
	ximpRec		decimal(5, 2),
	xtotaNoGrav	decimal(20,2),
	xtotFact	decimal(20, 2),
	xsaldo		decimal(20, 2),
	xusuario	varchar(5),
	xhost		varchar(50),
	xidTipoDoc	int,
	xnroDoc		varchar(20),
	xrazSoc		varchar(60)
)
BEGIN
	DECLARE vMensaje TEXT;
	DECLARE vProxID int;
	DECLARE vProxIdItems int;
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		GET DIAGNOSTICS CONDITION 1 vMensaje = MESSAGE_TEXT;
		INSERT INTO log_sps (sp_name, msgerror, usuario, host)
		VALUES ('ventas_generar_cbtes', vMensaje, xusuario, xhost);
		SELECT '0' AS 'result', vMensaje AS 'mensaje';
	END;
	
	START TRANSACTION;
	
	-- Calculo el próximo Id. de venta.
	SELECT
		CASE WHEN MAX(idVentasC) IS NULL THEN 1 ELSE MAX(idVentasC) + 1 END
	INTO
		vProxId
	FROM
		ventascab;
		
	-- Hago el INSERT INTO de la cabecera
	INSERT INTO ventascab (
		idVentasC,
		idCliente,
		idCondPago,
		idSitIVA,
		idVendedor,
		fecEmision,
		fecVto,
		cbte,
		tipoDoc,
		ptoVta,
		numCbte,
		impNeto,
		impFinal,
		porIVA21,
		impIVA21,
		porIVA105,
		impIVA105,
		porIIBB,
		impIIBB,
		porDesc1,
		impDesc1,
		porDesc2,
		impDesc2,
		porDesc3,
		impDesc3,
		porDesc4,
		impDesc4,
		porRec,
		impRec,
		totaNoGrav,
		totFact,
		saldo,
		usuAlta,
		fecAlta,
		idHostAlta,
		idTipoDoc,
		nroDoc,
		anulado,
		razSoc)
	VALUES (
		vProxID,
		xidCliente,
		xidCondPago,
		xidSitIVA,
		xidVendedor,
		xfecEmision,
		xfecVto,
		xcbte,
		xtipoDoc,
		xptoVta,
		xnumCbte,
		ximpNeto,
		ximpFinal,
		xporIVA21,
		ximpIVA21,
		xporIVA105,
		ximpIVA105,
		xporIIBB,
		ximpIIBB,
		xporDesc1,
		ximpDesc1,
		xporDesc2,
		ximpDesc2,
		xporDesc3,
		ximpDesc3,
		xporDesc4,
		ximpDesc4,
		xporRec,
		ximpRec,
		xtotaNoGrav,
		xtotFact,
		xsaldo,
		xusuario,
		current_timestamp,
		xhost,
		xidTipoDoc,
		xnroDoc,
		0,
		xrazSoc);	
		
	/* Genero el detalle del comprobante.*/
		
	-- Inserto los ítems a partir de la tabla temporal
	-- En la tabla temporal ya se cargan todos los datos calculados.
	INSERT INTO ventasdet (
		idVentasD,
		idVentasC,
		idArticulo,
		cantidad,
		cantNC,
		costoRep,
		prArtic,
		prVenta,
		porDesc1,
		porDesc2,
		porDesc3,
		porDesc4,
		impDesc1,
		impDesc2,
		impDesc3,
		impDesc4,
		pDtoVta1,
		pDtoVta2,
		pDtoVta3,
		pDtoVta4,
		iDtoVta1,
		iDtoVta2,
		iDtoVta3,
		iDtoVta4,
		impNeto,
		porNoGrav,
		baseGrav,
		subtNoGrav,
		totNeto,
		alicIVA,
		impIVA,
		subTotal,
		nroPart,
		esOferta,
		pRecVta,
		iRecVta,
		UniDesp,
		cantPack,
		codUM,
		cant_pri1,
		cant_pri2,
		cant_pri3,
		descripcio,
		cant_falt,
		pRecItem,
		iRecItem) 
			SELECT
				(@id := @id + 1),
				vProxID,
				idArticulo,
				cantidad,
				cantNC,
				costoRep,
				prArtic,
				prVenta,
				porDesc1,
				porDesc2,
				porDesc3,
				porDesc4,
				impDesc1,
				impDesc2,
				impDesc3,
				impDesc4,
				pDtoVta1,
				pDtoVta2,
				pDtoVta3,
				pDtoVta4,
				iDtoVta1,
				iDtoVta2,
				iDtoVta3,
				iDtoVta4,
				impNeto,
				porNoGrav,
				baseGrav,
				subtNoGrav,
				totNeto,
				alicIVA,
				impIVA,
				subTotal,
				nroPart,
				esOferta,
				pRecVta,
				iRecVta,
				UniDesp,
				cantPack,
				codUM,
				cant_pri1,
				cant_pri2,
				cant_pri3,
				descripcio,
				cant_falt,
				pRecItem,
				iRecItem
			FROM
				(
					SELECT
						@id := 0,
						idArticulo,
						cantidad,
						cantNC,
						costoRep,
						prArtic,
						prVenta,
						porDesc1,
						porDesc2,
						porDesc3,
						porDesc4,
						impDesc1,
						impDesc2,
						impDesc3,
						impDesc4,
						pDtoVta1,
						pDtoVta2,
						pDtoVta3,
						pDtoVta4,
						iDtoVta1,
						iDtoVta2,
						iDtoVta3,
						iDtoVta4,
						impNeto,
						porNoGrav,
						baseGrav,
						subtNoGrav,
						totNeto,
						alicIVA,
						impIVA,
						subTotal,
						nroPart,
						esOferta,
						pRecVta,
						iRecVta,
						UniDesp,
						cantPack,
						codUM,
						cant_pri1,
						cant_pri2,
						cant_pri3,
						descripcio,
						cant_falt,
						pRecItem,
						iRecItem
					FROM
						ventasdet_tmp
					WHERE
						host = xhost) ventasdet_tmp;
				
	COMMIT;
	SELECT vProxID AS 'result';
END