************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmconsingresos
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
list_cbtes = 'RTO'
Name = "frmconsingresos"
Contenedor1.Clsetiqueta3.Name = "Clsetiqueta3"
Contenedor1.Clsetiqueta4.Name = "Clsetiqueta4"
Contenedor1.txtFecDesde.Name = "txtFecDesde"
Contenedor1.txtFecHasta.Name = "txtFecHasta"
Contenedor1.Clsetiqueta5.Name = "Clsetiqueta5"
Contenedor1.txtPtoVta.Name = "txtPtoVta"
Contenedor1.cmbCbte.Name = "cmbCbte"
Contenedor1.cmbTipo.Name = "cmbTipo"
Contenedor1.txtnumero.Name = "txtnumero"
Contenedor1.grdRtos.COLUMN1.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN1.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN1.Name = "COLUMN1"
Contenedor1.grdRtos.COLUMN2.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN2.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN2.Name = "COLUMN2"
Contenedor1.grdRtos.COLUMN3.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN3.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN3.Name = "COLUMN3"
Contenedor1.grdRtos.COLUMN4.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN4.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN4.Name = "COLUMN4"
Contenedor1.grdRtos.COLUMN5.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN5.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN5.Name = "COLUMN5"
Contenedor1.grdRtos.COLUMN6.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN6.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN6.Name = "COLUMN6"
Contenedor1.grdRtos.COLUMN7.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN7.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN7.Name = "COLUMN7"
Contenedor1.grdRtos.COLUMN8.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN8.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN8.Name = "COLUMN8"
Contenedor1.grdRtos.COLUMN9.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN9.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN9.Name = "COLUMN9"
Contenedor1.grdRtos.COLUMN10.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN10.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN10.Name = "COLUMN10"
Contenedor1.grdRtos.COLUMN11.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN11.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN11.Name = "COLUMN11"
Contenedor1.grdRtos.COLUMN12.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN12.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN12.Name = "COLUMN12"
Contenedor1.grdRtos.COLUMN13.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN13.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN13.Name = "COLUMN13"
Contenedor1.grdRtos.COLUMN14.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN14.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN14.Name = "COLUMN14"
Contenedor1.grdRtos.COLUMN15.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN15.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN15.Name = "COLUMN15"
Contenedor1.grdRtos.COLUMN16.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN16.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN16.Name = "COLUMN16"
Contenedor1.grdRtos.COLUMN17.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN17.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN17.Name = "COLUMN17"
Contenedor1.grdRtos.COLUMN18.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN18.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN18.Name = "COLUMN18"
Contenedor1.grdRtos.COLUMN19.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN19.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN19.Name = "COLUMN19"
Contenedor1.grdRtos.COLUMN20.Header1.Name = "Header1"
Contenedor1.grdRtos.COLUMN20.Text1.Name = "Text1"
Contenedor1.grdRtos.COLUMN20.Name = "COLUMN20"
Contenedor1.grdRtos.Name = "grdRtos"
Contenedor1.btnSalir.Name = "btnSalir"
Contenedor1.btnBuscar.Name = "btnBuscar"
Contenedor1.CLSETIQUETA1.Name = "CLSETIQUETA1"
Contenedor1.grdDetalle.COLUMN1.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN1.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN1.Name = "COLUMN1"
Contenedor1.grdDetalle.COLUMN2.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN2.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN2.Name = "COLUMN2"
Contenedor1.grdDetalle.COLUMN3.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN3.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN3.Name = "COLUMN3"
Contenedor1.grdDetalle.COLUMN4.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN4.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN4.Name = "COLUMN4"
Contenedor1.grdDetalle.COLUMN5.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN5.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN5.Name = "COLUMN5"
Contenedor1.grdDetalle.COLUMN6.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN6.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN6.Name = "COLUMN6"
Contenedor1.grdDetalle.COLUMN7.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN7.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN7.Name = "COLUMN7"
Contenedor1.grdDetalle.COLUMN8.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN8.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN8.Name = "COLUMN8"
Contenedor1.grdDetalle.COLUMN9.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN9.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN9.Name = "COLUMN9"
Contenedor1.grdDetalle.COLUMN10.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN10.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN10.Name = "COLUMN10"
Contenedor1.grdDetalle.COLUMN11.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN11.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN11.Name = "COLUMN11"
Contenedor1.grdDetalle.COLUMN12.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN12.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN12.Name = "COLUMN12"
Contenedor1.grdDetalle.COLUMN13.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN13.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN13.Name = "COLUMN13"
Contenedor1.grdDetalle.COLUMN14.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN14.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN14.Name = "COLUMN14"
Contenedor1.grdDetalle.COLUMN15.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN15.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN15.Name = "COLUMN15"
Contenedor1.grdDetalle.COLUMN16.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN16.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN16.Name = "COLUMN16"
Contenedor1.grdDetalle.COLUMN17.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN17.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN17.Name = "COLUMN17"
Contenedor1.grdDetalle.COLUMN18.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN18.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN18.Name = "COLUMN18"
Contenedor1.grdDetalle.COLUMN19.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN19.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN19.Name = "COLUMN19"
Contenedor1.grdDetalle.COLUMN20.Header1.Name = "Header1"
Contenedor1.grdDetalle.COLUMN20.Text1.Name = "Text1"
Contenedor1.grdDetalle.COLUMN20.Name = "COLUMN20"
Contenedor1.grdDetalle.Name = "grdDetalle"
Contenedor1.sel_prov_desde.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_prov_desde.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_prov_desde.Name = "sel_prov_desde"
Contenedor1.sel_prov_hasta.txtCodigo.Name = "txtCodigo"
Contenedor1.sel_prov_hasta.txtDescripcion.Name = "txtDescripcion"
Contenedor1.sel_prov_hasta.Name = "sel_prov_hasta"
Contenedor1.Clsetiqueta2.Name = "Clsetiqueta2"
Contenedor1.Clsetiqueta8.Name = "Clsetiqueta8"
Contenedor1.Name = "Contenedor1"
Clsimprimir1.Name = "Clsimprimir1"
OINGMERC.Name = "OINGMERC"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0

*** METODOS ***


