************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frm_orden_pago
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frm_orden_pago"
contenido.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.sel_prov.txtCodigo.Name = "txtCodigo"
contenido.sel_prov.txtDescripcion.Name = "txtDescripcion"
contenido.sel_prov.Name = "sel_prov"
contenido.pgroup.ErasePage = .T.
contenido.pgroup.Page1.grdComprobantes.Column1.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column1.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column1.Name = "Column1"
contenido.pgroup.Page1.grdComprobantes.Column2.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column2.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column2.Name = "Column2"
contenido.pgroup.Page1.grdComprobantes.Column3.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column3.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column3.Name = "Column3"
contenido.pgroup.Page1.grdComprobantes.Column4.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column4.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column4.Name = "Column4"
contenido.pgroup.Page1.grdComprobantes.Column5.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column5.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column5.Name = "Column5"
contenido.pgroup.Page1.grdComprobantes.Column6.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column6.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column6.Name = "Column6"
contenido.pgroup.Page1.grdComprobantes.Column7.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column7.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column7.Name = "Column7"
contenido.pgroup.Page1.grdComprobantes.Column8.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column8.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column8.Name = "Column8"
contenido.pgroup.Page1.grdComprobantes.Column9.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column9.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column9.Name = "Column9"
contenido.pgroup.Page1.grdComprobantes.Column10.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column10.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column10.Name = "Column10"
contenido.pgroup.Page1.grdComprobantes.Column11.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column11.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column11.Name = "Column11"
contenido.pgroup.Page1.grdComprobantes.Column12.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column12.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column12.Name = "Column12"
contenido.pgroup.Page1.grdComprobantes.Column13.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column13.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column13.Name = "Column13"
contenido.pgroup.Page1.grdComprobantes.Column14.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column14.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column14.Name = "Column14"
contenido.pgroup.Page1.grdComprobantes.Column15.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column15.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column15.Name = "Column15"
contenido.pgroup.Page1.grdComprobantes.Column16.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column16.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column16.Name = "Column16"
contenido.pgroup.Page1.grdComprobantes.Column17.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column17.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column17.Name = "Column17"
contenido.pgroup.Page1.grdComprobantes.Column18.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column18.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column18.Name = "Column18"
contenido.pgroup.Page1.grdComprobantes.Column19.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column19.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column19.Name = "Column19"
contenido.pgroup.Page1.grdComprobantes.Column20.Header1.Name = "Header1"
contenido.pgroup.Page1.grdComprobantes.Column20.Text1.Name = "Text1"
contenido.pgroup.Page1.grdComprobantes.Column20.Name = "Column20"
contenido.pgroup.Page1.grdComprobantes.Height = 378
contenido.pgroup.Page1.grdComprobantes.Left = 8
contenido.pgroup.Page1.grdComprobantes.Top = 10
contenido.pgroup.Page1.grdComprobantes.Width = 905
contenido.pgroup.Page1.grdComprobantes.Name = "grdComprobantes"
contenido.pgroup.Page1.Name = "Page1"
contenido.pgroup.Page2.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgroup.Page2.cmbConcepto.Name = "cmbConcepto"
contenido.pgroup.Page2.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgroup.Page2.txtImporte.Name = "txtImporte"
contenido.pgroup.Page2.Name = "Page2"
contenido.pgroup.Page3.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgroup.Page3.grdChequesDisp.Column1.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column1.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column1.Name = "Column1"
contenido.pgroup.Page3.grdChequesDisp.Column2.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column2.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column2.Name = "Column2"
contenido.pgroup.Page3.grdChequesDisp.Column3.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column3.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column3.Name = "Column3"
contenido.pgroup.Page3.grdChequesDisp.Column4.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column4.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column4.Name = "Column4"
contenido.pgroup.Page3.grdChequesDisp.Column5.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column5.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column5.Name = "Column5"
contenido.pgroup.Page3.grdChequesDisp.Column6.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column6.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column6.Name = "Column6"
contenido.pgroup.Page3.grdChequesDisp.Column7.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column7.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column7.Name = "Column7"
contenido.pgroup.Page3.grdChequesDisp.Column8.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column8.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column8.Name = "Column8"
contenido.pgroup.Page3.grdChequesDisp.Column9.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column9.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column9.Name = "Column9"
contenido.pgroup.Page3.grdChequesDisp.Column10.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column10.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column10.Name = "Column10"
contenido.pgroup.Page3.grdChequesDisp.Column11.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column11.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column11.Name = "Column11"
contenido.pgroup.Page3.grdChequesDisp.Column12.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column12.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column12.Name = "Column12"
contenido.pgroup.Page3.grdChequesDisp.Column13.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column13.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column13.Name = "Column13"
contenido.pgroup.Page3.grdChequesDisp.Column14.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column14.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column14.Name = "Column14"
contenido.pgroup.Page3.grdChequesDisp.Column15.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column15.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column15.Name = "Column15"
contenido.pgroup.Page3.grdChequesDisp.Column16.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column16.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column16.Name = "Column16"
contenido.pgroup.Page3.grdChequesDisp.Column17.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column17.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column17.Name = "Column17"
contenido.pgroup.Page3.grdChequesDisp.Column18.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column18.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column18.Name = "Column18"
contenido.pgroup.Page3.grdChequesDisp.Column19.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column19.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column19.Name = "Column19"
contenido.pgroup.Page3.grdChequesDisp.Column20.Header1.Name = "Header1"
contenido.pgroup.Page3.grdChequesDisp.Column20.Text1.Name = "Text1"
contenido.pgroup.Page3.grdChequesDisp.Column20.Name = "Column20"
contenido.pgroup.Page3.grdChequesDisp.Height = 326
contenido.pgroup.Page3.grdChequesDisp.Left = 16
contenido.pgroup.Page3.grdChequesDisp.Top = 30
contenido.pgroup.Page3.grdChequesDisp.Width = 877
contenido.pgroup.Page3.grdChequesDisp.Name = "grdChequesDisp"
contenido.pgroup.Page3.Clsetiqueta2.Left = 18
contenido.pgroup.Page3.Clsetiqueta2.Top = 365
contenido.pgroup.Page3.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgroup.Page3.txtImpTotCheq.Left = 120
contenido.pgroup.Page3.txtImpTotCheq.Top = 361
contenido.pgroup.Page3.txtImpTotCheq.Name = "txtImpTotCheq"
contenido.pgroup.Page3.Name = "Page3"
contenido.pgroup.Page4.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgroup.Page4.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgroup.Page4.Clsetiqueta4.Name = "Clsetiqueta4"
contenido.pgroup.Page4.txtNroTrans.Name = "txtNroTrans"
contenido.pgroup.Page4.txtOriginante.Name = "txtOriginante"
contenido.pgroup.Page4.Clsetiqueta6.Name = "Clsetiqueta6"
contenido.pgroup.Page4.Clsagregar1.Name = "Clsagregar1"
contenido.pgroup.Page4.Gridcontrol1.Column1.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column1.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column1.Name = "Column1"
contenido.pgroup.Page4.Gridcontrol1.Column2.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column2.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column2.Name = "Column2"
contenido.pgroup.Page4.Gridcontrol1.Column3.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column3.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column3.Name = "Column3"
contenido.pgroup.Page4.Gridcontrol1.Column4.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column4.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column4.Name = "Column4"
contenido.pgroup.Page4.Gridcontrol1.Column5.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column5.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column5.Name = "Column5"
contenido.pgroup.Page4.Gridcontrol1.Column6.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column6.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column6.Name = "Column6"
contenido.pgroup.Page4.Gridcontrol1.Column7.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column7.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column7.Name = "Column7"
contenido.pgroup.Page4.Gridcontrol1.Column8.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column8.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column8.Name = "Column8"
contenido.pgroup.Page4.Gridcontrol1.Column9.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column9.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column9.Name = "Column9"
contenido.pgroup.Page4.Gridcontrol1.Column10.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column10.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column10.Name = "Column10"
contenido.pgroup.Page4.Gridcontrol1.Column11.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column11.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column11.Name = "Column11"
contenido.pgroup.Page4.Gridcontrol1.Column12.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column12.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column12.Name = "Column12"
contenido.pgroup.Page4.Gridcontrol1.Column13.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column13.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column13.Name = "Column13"
contenido.pgroup.Page4.Gridcontrol1.Column14.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column14.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column14.Name = "Column14"
contenido.pgroup.Page4.Gridcontrol1.Column15.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column15.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column15.Name = "Column15"
contenido.pgroup.Page4.Gridcontrol1.Column16.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column16.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column16.Name = "Column16"
contenido.pgroup.Page4.Gridcontrol1.Column17.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column17.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column17.Name = "Column17"
contenido.pgroup.Page4.Gridcontrol1.Column18.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column18.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column18.Name = "Column18"
contenido.pgroup.Page4.Gridcontrol1.Column19.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column19.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column19.Name = "Column19"
contenido.pgroup.Page4.Gridcontrol1.Column20.Header1.Name = "Header1"
contenido.pgroup.Page4.Gridcontrol1.Column20.Text1.Name = "Text1"
contenido.pgroup.Page4.Gridcontrol1.Column20.Name = "Column20"
contenido.pgroup.Page4.Gridcontrol1.Height = 258
contenido.pgroup.Page4.Gridcontrol1.Left = 26
contenido.pgroup.Page4.Gridcontrol1.Top = 131
contenido.pgroup.Page4.Gridcontrol1.Width = 862
contenido.pgroup.Page4.Gridcontrol1.Name = "Gridcontrol1"
contenido.pgroup.Page4.sel_banco.txtCodigo.Name = "txtCodigo"
contenido.pgroup.Page4.sel_banco.txtDescripcion.Name = "txtDescripcion"
contenido.pgroup.Page4.sel_banco.Name = "sel_banco"
contenido.pgroup.Page4.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.pgroup.Page4.Clsetiqueta5.Name = "Clsetiqueta5"
contenido.pgroup.Page4.txtFecha.Name = "txtFecha"
contenido.pgroup.Page4.txtDocumento.Name = "txtDocumento"
contenido.pgroup.Page4.txtImporte.Name = "txtImporte"
contenido.pgroup.Page4.CLSCANCELAR1.Name = "CLSCANCELAR1"
contenido.pgroup.Page4.Name = "Page4"
contenido.pgroup.Page5.Clsetiqueta1.Name = "Clsetiqueta1"
contenido.pgroup.Page5.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.pgroup.Page5.Clsetiqueta3.Name = "Clsetiqueta3"
contenido.pgroup.Page5.Clsetiqueta4.Name = "Clsetiqueta4"
contenido.pgroup.Page5.Clsetiqueta5.Name = "Clsetiqueta5"
contenido.pgroup.Page5.txtIVA.Name = "txtIVA"
contenido.pgroup.Page5.txtIIBB.Name = "txtIIBB"
contenido.pgroup.Page5.cboProvincia.Name = "cboProvincia"
contenido.pgroup.Page5.txtGanancias.Name = "txtGanancias"
contenido.pgroup.Page5.txtSUSS.Name = "txtSUSS"
contenido.pgroup.Page5.Name = "Page5"
contenido.pgroup.Name = "pgroup"
contenido.Clsetiqueta2.Name = "Clsetiqueta2"
contenido.txtTotImputar.Name = "txtTotImputar"
contenido.btnGrabar.Name = "btnGrabar"
contenido.btnCerrar.Name = "btnCerrar"
contenido.Name = "contenido"

*** METODOS ***


************************************************************
OBJETO: orden_pago
************************************************************
*** PROPIEDADES ***
Top = 468
Left = 12
Height = 17
Width = 23
Name = "orden_pago"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


