************************************************************
OBJETO: Dataenvironment
************************************************************
*** PROPIEDADES ***
Top = 0
Left = 0
Width = 0
Height = 0
DataSource = .NULL.
Name = "Dataenvironment"

*** METODOS ***


************************************************************
OBJETO: frmabmtiposrep
************************************************************
*** PROPIEDADES ***
DoCreate = .T.
Name = "frmabmtiposrep"
Herramientas.cmdNuevo.Name = "cmdNuevo"
Herramientas.cmdEditar.Name = "cmdEditar"
Herramientas.cmdEliminar.Name = "cmdEliminar"
Herramientas.cmdCerrar.Name = "cmdCerrar"
Herramientas.cmdGrabar.Name = "cmdGrabar"
Herramientas.cmdCancelar.Name = "cmdCancelar"
Herramientas.cmdExcel.Name = "cmdExcel"
Herramientas.Name = "Herramientas"
Pgf.ErasePage = .T.
Pgf.Page1.grdDatos.COLUMN1.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN1.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN1.Name = "COLUMN1"
Pgf.Page1.grdDatos.COLUMN2.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN2.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN2.Name = "COLUMN2"
Pgf.Page1.grdDatos.COLUMN3.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN3.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN3.Name = "COLUMN3"
Pgf.Page1.grdDatos.COLUMN4.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN4.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN4.Name = "COLUMN4"
Pgf.Page1.grdDatos.COLUMN5.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN5.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN5.Name = "COLUMN5"
Pgf.Page1.grdDatos.COLUMN6.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN6.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN6.Name = "COLUMN6"
Pgf.Page1.grdDatos.COLUMN7.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN7.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN7.Name = "COLUMN7"
Pgf.Page1.grdDatos.COLUMN8.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN8.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN8.Name = "COLUMN8"
Pgf.Page1.grdDatos.COLUMN9.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN9.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN9.Name = "COLUMN9"
Pgf.Page1.grdDatos.COLUMN10.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN10.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN10.Name = "COLUMN10"
Pgf.Page1.grdDatos.COLUMN11.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN11.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN11.Name = "COLUMN11"
Pgf.Page1.grdDatos.COLUMN12.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN12.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN12.Name = "COLUMN12"
Pgf.Page1.grdDatos.COLUMN13.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN13.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN13.Name = "COLUMN13"
Pgf.Page1.grdDatos.COLUMN14.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN14.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN14.Name = "COLUMN14"
Pgf.Page1.grdDatos.COLUMN15.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN15.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN15.Name = "COLUMN15"
Pgf.Page1.grdDatos.COLUMN16.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN16.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN16.Name = "COLUMN16"
Pgf.Page1.grdDatos.COLUMN17.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN17.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN17.Name = "COLUMN17"
Pgf.Page1.grdDatos.COLUMN18.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN18.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN18.Name = "COLUMN18"
Pgf.Page1.grdDatos.COLUMN19.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN19.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN19.Name = "COLUMN19"
Pgf.Page1.grdDatos.COLUMN20.Header1.Name = "Header1"
Pgf.Page1.grdDatos.COLUMN20.Text1.Name = "Text1"
Pgf.Page1.grdDatos.COLUMN20.Name = "COLUMN20"
Pgf.Page1.grdDatos.Name = "grdDatos"
Pgf.Page1.Name = "Page1"
Pgf.Page2.cnt_fields.etiqDescrip_TipoRep.Name = "etiqDescrip_TipoRep"
Pgf.Page2.cnt_fields.txtDescrip_TipoRep.Name = "txtDescrip_TipoRep"
Pgf.Page2.cnt_fields.Clsetiqueta1.Name = "Clsetiqueta1"
Pgf.Page2.cnt_fields.txtCodigoTR.Name = "txtCodigoTR"
Pgf.Page2.cnt_fields.chkInclurR.Alignment = 0
Pgf.Page2.cnt_fields.chkInclurR.Name = "chkInclurR"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN1.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN1.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN1.Name = "COLUMN1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN2.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN2.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN2.Name = "COLUMN2"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN3.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN3.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN3.Name = "COLUMN3"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN4.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN4.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN4.Name = "COLUMN4"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN5.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN5.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN5.Name = "COLUMN5"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN6.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN6.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN6.Name = "COLUMN6"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN7.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN7.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN7.Name = "COLUMN7"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN8.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN8.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN8.Name = "COLUMN8"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN9.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN9.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN9.Name = "COLUMN9"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN10.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN10.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN10.Name = "COLUMN10"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN11.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN11.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN11.Name = "COLUMN11"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN12.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN12.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN12.Name = "COLUMN12"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN13.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN13.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN13.Name = "COLUMN13"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN14.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN14.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN14.Name = "COLUMN14"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN15.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN15.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN15.Name = "COLUMN15"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN16.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN16.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN16.Name = "COLUMN16"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN17.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN17.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN17.Name = "COLUMN17"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN18.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN18.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN18.Name = "COLUMN18"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN19.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN19.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN19.Name = "COLUMN19"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN20.Header1.Name = "Header1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN20.Text1.Name = "Text1"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.COLUMN20.Name = "COLUMN20"
Pgf.Page2.cnt_fields.CNT_piezas.grdPiezas.Name = "grdPiezas"
Pgf.Page2.cnt_fields.CNT_piezas.etiqpieza.Name = "etiqpieza"
Pgf.Page2.cnt_fields.CNT_piezas.txtCant_Pieza.Name = "txtCant_Pieza"
Pgf.Page2.cnt_fields.CNT_piezas.etiqCantidad.Name = "etiqCantidad"
Pgf.Page2.cnt_fields.CNT_piezas.sel_piezas.TXTCODIGO.Name = "TXTCODIGO"
Pgf.Page2.cnt_fields.CNT_piezas.sel_piezas.txtDescripcion.Name = "txtDescripcion"
Pgf.Page2.cnt_fields.CNT_piezas.sel_piezas.Name = "sel_piezas"
Pgf.Page2.cnt_fields.CNT_piezas.btnEliminar.Name = "btnEliminar"
Pgf.Page2.cnt_fields.CNT_piezas.btnAgregar.Name = "btnAgregar"
Pgf.Page2.cnt_fields.CNT_piezas.Name = "CNT_piezas"
Pgf.Page2.cnt_fields.Name = "cnt_fields"
Pgf.Page2.Name = "Page2"
Pgf.Name = "Pgf"

*** METODOS ***


************************************************************
OBJETO: 
************************************************************
*** PROPIEDADES ***
Arial, 0, 8, 5, 14, 11, 29, 3, 0
Arial, 0, 9, 5, 15, 12, 32, 3, 0
Arial, 1, 8, 5, 14, 11, 29, 3, 0

*** METODOS ***


